# Docker image
FROM mongo:6.0

# Environment vars config
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=admin

# Port of de container
EXPOSE 27017

# Execution of the DB
CMD ["mongod"]